### ISSUE TITLE
Link To / Integrate http://testers.perl6.org/

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#10]
The modules page should at the very least link to http://testers.perl6.org/

But if it could somehow incorporate those `PASS Ratio` graphs that would be fantastic.

**Comment by azawawi** [comment]
This is an interesting one. I guess we need to modify http://testers.perl6.org/ to provide some pass ratio graph API first.

**Comment by zoffixznet** [comment]
This is superceeded by the PAUSE/CPAN/MetaCPAN efforts. Closing.
