### ISSUE TITLE
Possible Missing Modules

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#11]
If we look at [ecosystem list](https://github.com/perl6/ecosystem/blob/master/META.list), there are currently `389` lines.

The [newly added module count](https://github.com/perl6/modules.perl6.org/commit/15f1eb78797f5546518230e875a3daf851f11a6a) shows `385` modules.

And the page apparently lists only `382` modules based on running
```bash
perl -MMojo::UserAgent -wlE 'say Mojo::UserAgent->new->get("http://modules.perl6.org/")->res->dom->find(".name")->size'
```

The data shows there are `7` modules missing from the final list; being lost at various stages of the process.

**Comment by moritz** [comment]
http://ecosystem-api.p6c.org/errors.json shows that Leont/yamlish/META.info isn't valid JSON, which accounts for the first :-)

**Comment by zoffixznet** [comment]
Another one was was invalid URL in Math-Odd-Functions in ecosystem (Fixed). So that's 2 :)

**Comment by zoffixznet** [comment]
All the missing modules have been located using this little script: https://github.com/zoffixznet/perl6-util-Check-Modules-Perl6-Org

Will investigate why the missing ones are missing...

```bash
https://raw.githubusercontent.com/FROGGS/p6-Foo-v1.2.0/master/META.info has the same name [Foo] as https://raw.githubusercontent.com/FROGGS/p6-Foo-v1.0.0/master/META.info!

https://raw.githubusercontent.com/tokuhirom/p6-HTTP-MultiPartParser/master/META6.json [HTTP::MultiPartParser] not found on modules.perl6.org!

https://raw.githubusercontent.com/tokuhirom/p6-Cookie-Baker/master/META6.json [Cookie::Baker] not found on modules.perl6.org!

https://raw.githubusercontent.com/tokuhirom/p6-HTTP-Parser/master/META6.json [HTTP::Parser] not found on modules.perl6.org!

https://raw.githubusercontent.com/stmuk/p6-eco-readme/master/META.info [App::ecoreadme] not found on modules.perl6.org!
```

**Comment by moritz** [comment]
Some more log entries:

    Invalid json found at: https://raw.githubusercontent.com/Leont/yamlish/master/META.info
    Invalid source-url found:  git@github.com:stmuk/p6-eco-readme.git (https://raw.githubusercontent.com/stmuk/p6-eco-readme/master/META.info)
    Error for project IO::Path::More : could not get https://api.github.com/repos///commits: 404 Not Found
    Error decoding content: Cannot decode string with wide characters at /usr/lib/x86_64-linux-gnu/perl/5.20/Encode.pm line 215.

I'll try to make the logs available automatically

**Comment by moritz** [comment]
http://modules.perl6.org/log/update.log now has the full output from web/build-project-list.pl; feel free to make that script more verbose if you need more debugging output.

(Though of course you can also run that script locally, you just have to provide it with a github API key, iirc)
