### ISSUE TITLE
Too many Travis badges result in 429s

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#12]
@szabgab there's a problem with the current implementation of Travis badges. Travis doesn't seem to like 385+ simultaneous requests for badges and responds with 429s (HTTP Too Many Requests).

We need to amend the implementation and only show badges on request for specific modules (on-click or on-hover). Then users would be able to look up build status on a module they're interested in

![trav](https://cloud.githubusercontent.com/assets/5747918/10412954/e5f64a0e-6f65-11e5-87b3-f826f8968cf7.png)

**Comment by szabgab** [comment]
It's only about 80 requests as only that many modules have travis enabled, but that still means we have to find another solution. Maybe we can fetch the Travis status when updating the site and then only link to Travis and show the appropriate version of the Travis badge.

**Comment by zoffixznet** [comment]
This has been fixed in https://github.com/perl6/modules.perl6.org/commit/56379cc251f0d4704843c1a41c6727de2947e69f
