### ISSUE TITLE
META-LIST.json file that contains all available modules

### ISSUE THREAD

**Issue by hythm7** [perl6/modules.perl6.org#126]
Is there a url one can access to request all the META6.json files contents for all available modules? Something like a json array that contains all meta files? (the contents not the url of the META6.josn files)

**Comment by Altai-man** [comment]
https://ecosystem-api.p6c.org/projects.json
https://ecosystem-api.p6c.org/projects1.json
?

**Comment by AlexDaniel** [comment]
IIRC you need both of these:
*    https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
*    https://ecosystem-api.p6c.org/projects.json

**Comment by hythm7** [comment]
Right I'm aware of these two files, but does it make sense to have them hosted somewhere in modules.perl6.org (separate files or combined in one file) rather than a github link?

**Comment by Altai-man** [comment]
>Right I'm aware of these two files, but does it make sense to have them hosted somewhere in modules.perl6.org (separate files or combined in one file) rather than a github link?

Well, they are hosted on our infrastructure server. Though the practice has shown having a github backup is helpful too.

**Comment by hythm7** [comment]
> Well, they are hosted on our infrastructure server. Though the practice has shown having a github backup is helpful too.

May be I'm missing something, the github link doesn't have equivalence hosted on the infrastructure, so it's not a backup. it contains modules that are not existing in any of the other links above. for example `Path::Through`.

**Comment by AlexDaniel** [comment]
Yep, they are different files, and I don't know of a self-hosted alternative for that github link.

**Comment by AlexDaniel** [comment]
Ping @rba
