### ISSUE TITLE
List "originally added date" for modules

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#14]
(this was wishlisted on https://github.com/perl6/ecosystem/issues/76#issuecomment-147810235)

The `recent` page exists, but it's currently pretty unknown and I don't see it linked to from anywhere on http://modules.perl6.org/recent.html

Alternatively, why not get rid of `recent.html` and just make the module list sortable?

**Comment by jonathanstowe** [comment]
I'd go with making the list sortable :)  Also, an originally added date as well as updated somewhere in the data might be useful

**Comment by zoffixznet** [comment]
> an originally added date

That still needs to be added to close this Issue

**Comment by azawawi** [comment]
What about using `created_at` github repo key? But that's repository creation date.

I do not see how we can determine ecosystem addition date.

**Comment by jonathanstowe** [comment]
I think that would be a bit misleading as I have things that are not yet released where the repository was created six months ago,  a "first seen" might be a better analogue.  In the P6Project::Info->get_projects it has the existing proto.json in hand while it is creating the new data, it could just check whether it is *new* project and put the current date in :)  Obviously some heuristic may be required for back-filling the existing entries.
