### ISSUE TITLE
Add link to raku.land

### ISSUE THREAD

**Issue by coke** [perl6/modules.perl6.org#146]
As https://github.com/Raku/problem-solving/pull/331 languishes, a quick hit might be to link to raku.land in the header of this site.

**Comment by dontlaugh** [comment]
Note that this site now redirects to raku.land; This step was taken today so that modules.raku.org points to _something_ after the catastrophic failure of a donated server box that hosted half a dozen community projects. See also https://github.com/rakudo/rakudo.org/issues/94.
