### ISSUE TITLE
Perform search if search box contains text on page load

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#15]
Currently, if you do a search -> visit a module -> hit browser Back button, you're shown all modules instead of search results.

**Comment by jonathanstowe** [comment]
It actually does similar when you back when you haven't searched (it just goes back to the top of the list rather than where you had scrolled to,) it wasn't a problem originally but now there are more than a few modules it's a bit of a pain.

**Comment by zoffixznet** [comment]
The case @jonathanstowe mentioned should be fixed now too.

**Comment by jonathanstowe** [comment]
:+1:
