### ISSUE TITLE
Project: Document All Modules

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#16]
### The Problem

There are many modules in the ecosystem that lack any useful documentation. I've actually heard someone refer to this as "Perl 6's culture of no documentation."

### The Solution

We're about to have many new comers and having a simple way to contribute would be [good for the growth of the community](http://sarah.thesharps.us/2015/10/06/what-makes-a-good-community/).

1) Same as with the [Most Wanted Modules Wiki](https://github.com/perl6/perl6-most-wanted/blob/master/most-wanted/modules.md), we should have one for *Documentation Wanted*. 
2) Those who are new to the language could study those modules, figure out how they work, document the behaviour, and submit a doc PR.

In summation, I think this can be a great entry-level task for new comers to contribute to, while at the same time eradicating the "no documentation culture".

**Comment by jonathanstowe** [comment]
Someone needs to make something that does something like Pod::Coverage :)

**Comment by jonathanstowe** [comment]
but :+1:

**Comment by zoffixznet** [comment]
:+1: on making Pod::Coverage :p

**Comment by dwarring** [comment]
Would the idea be to add another badge which is displayed when documentation is present and passes coverage tests?

**Comment by jonathanstowe** [comment]
That could work

**Comment by dha** [comment]
There was discussion on IRC of making a list of the documentation status of modules. What would be a good place to put such a list for people to see/contribute to?

**Comment by zoffixznet** [comment]
I think a wiki-like thing akin to [Most Wanted](https://github.com/perl6/perl6-most-wanted/blob/master/most-wanted/modules.md) could be ideal.

**Comment by zoffixznet** [comment]
Since we're soon gonna switch to a Mojolicious-power app instead of static files, I think we could add something easier to use than a wiki hosted else-where. Something like a flag users could click if module's misssing docs.

And at the top of the page we could have some call to action, like "Looking for an easy way to contribute?" and people click on it and get a list of all the modules without docs that they could write up and then unlag the module.

**Comment by teodozjan** [comment]
Hi,

This is result of an one hour experiment https://github.com/teodozjan/pod6-coverage

Sample results:

     perl6 Pod/Coverage.pm6
      what isPerl6::Metamodel::ParametricRoleGroupHOW.new ?
      (Logic) Package
       (LacunaCookbuk::Logic::IntelCritic) class is not documented
       (LacunaCookbuk::Logic::Ambassador) class is not documented
       (LacunaCookbuk::Logic::Transporter) class is not documented
       (LacunaCookbuk::Logic::ShipCritic) class is not documented
       (LacunaCookbuk::Logic::Secretary) class is not documented
       (LacunaCookbuk::Logic::OreCritic) class is not documented
       (LacunaCookbuk::Logic::Commander) class is not documented
       (LacunaCookbuk::Logic::PlanMaker) class is not documented
      (Model) Package
       (Structure) Package
        (LacunaCookbuk::Model::Structure::BuildingView) class is not documented

 If you like I can go further or someone can fork it

**Comment by zoffixznet** [comment]
That's great! Yes, please go further :) As stated above, for start, we really just need something that tries to work, not a comprehensive error-prone solution :smile_cat: 

:shipit:

**Comment by teodozjan** [comment]
Hi, I've tried my best to provide coverage but I see little issue about noninline documentation.

There several ways people do their documentation.

JSON::RPC is documented inside README
DBIsh uses EOF pod for major classes
File::Find uses EOF pod mentioning method as C<>
also someone used headers to document subs/methods 

Are we going to support anything? Or just cover some standard?

**Comment by awwaiid** [comment]
I think any pod in the main lib or bin dirs would be a good start.

**Comment by teodozjan** [comment]
@awwaiid I added option option to check for pod inside provides files https://github.com/teodozjan/pod6-coverage/commit/84517d8859f2603ff5941b7150394beee0336110 what do you think about that?

**Comment by jonathanstowe** [comment]
Hi,
would it be possible to refactor the way it checks and then outputs the results such that it could be used in test file?  e.g. something eventually returns a list of objects with "what", "name","has-pod" attributes then one could do something like:

```

ok $obj.has-pod, " { $obj.what }  { $obj.name } has pod";

```

**Comment by zoffixznet** [comment]
> something eventually returns a list of objects

I'd expect the interface to be a single sub call and just prints TAP results. akin to [P5's version](https://metacpan.org/pod/Test::Pod::Coverage). Is there a need to manually write the `ok`?

**Comment by jonathanstowe** [comment]
Yes and "P5's version"  A) uses Pod::Coverage (a separate module) which returns the data as I described and B) uses Test::Builder to generate the results. You appear to be dis-agreeing with something I didn't say.

**Comment by teodozjan** [comment]
I thought users will just want to pass meta and get report with maybe boolean result. Now everything changed. Test builder sound good. I can also flatten different @!results and give them through method.


https://github.com/teodozjan/pod6-coverage/commit/d48ef59ab185810071233f09f56a4901c16c0ae7

**Comment by jonathanstowe** [comment]
I've used the P5 Pod::Coverage in the past to do things other than test (perhaps to generate stub entries for the documentation or something.) Splitting the interface, such that there is one part that actually does the checking and another part that uses that to compile the test results allows people to create alternative interfaces (such as e.g. class based testing or something similar.)

**Comment by zoffixznet** [comment]
@jonathanstowe I wasn't disagreeing but merely asking. Discussing all the merits prior to implementing them produces a cleaner and well-thought-out interface. I don't know why you consistently seem to be taking my attempts to do so as personal attacks.

**Comment by jonathanstowe** [comment]
I was merely suggesting there should be something like:

```
sub get-results( ... ) {  # returns list of result objects
....
}

sub test-coverage() {
    for get-results() -> $obj {
       ok $obj.has-pod, " { $obj.what }  { $obj.name } has pod";
    } 
}
```

The get-results can even be optionally exported.

I wasn't taking your words in any way except that they seemed to misunderstand what I had typed, but hey it's the weekend and I'm tired so maybe it's me.

**Comment by Skarsnik** [comment]
A big step would be to try to remove everything that does something like:
Impletement Perl5 Foo::Bar, see p5 documentation.

Or having a way to import these doc easily?

**Comment by teodozjan** [comment]
@Skarsnik That's why I propose to check it's completeness not only the presence

@jonathanstowe I modified class to use instance of pod Coverage per ::($str). Public `@.results` attribute contains anything wrong with package with also `are-missing` gives boolean result. It should be easy to write TAP support. Only `coverage` method that creates instance has little complicated arguments.

One thing I really like to have policy if is visible to user -> must be documented. Anyway I distinguish require string, package to check and file where code lies. Maybe someone can rewrite it to be simpler for example with compunitrepo? I still did not invent how to get EOF pod for class/module while it does not have to be Module::Name::Classname.pm6

**Comment by jonathanstowe** [comment]
Looks good :+1:

**Comment by teodozjan** [comment]
Finally Pod::Coverage is travis capable. So I made it work but I cannot say it works right.

It can take metafile and check if things in provide section contain any pod. So anypod name felt fine here for me.

It can traverse  into package documentation without thinking how deep is object inside package(maybe should be configurable) and check for .WHY

It reads pod only relying on headers and its level. I'm thnking about looking for NAME SYNOPSIS and METHODS header in future.

It has hacky implementation of TAP. `anypod_ok` `subtest_anypod_ok` and `coverage_ok` `subtest_coverage_ok`

**Comment by zoffixznet** [comment]
:+1: awesome!

**Comment by jonathanstowe** [comment]
I think it's time to try it out :)

Nice one :+1:

**Comment by Tux** [comment]
```
$ pod-coverage
Could not find Text::CSV in any of:
  file#/home/merijn/.perl6/2015.10-328-g3177463/lib
  inst#/home/merijn/.perl6/2015.10-328-g3177463
  file#/pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6/lib
  file#/pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6/vendor/lib
  file#/pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6/site/lib
  inst#/pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6
  inst#/pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6/vendor
  inst#/pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6/site
  in method coverage at /pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6/site/lib/Pod/Coverage.pm6:83
  in block  at /pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6/site/lib/Pod/Coverage.pm6:59
  in method use-meta at /pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6/site/lib/Pod/Coverage.pm6:57
  in sub MAIN at /pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6/site/bin/pod-coverage:7
  in block <unit> at /pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6/site/bin/pod-coverage:6

Exit 1
$ find * -name CSV.pm | xargs ls -l
lrwxrwxrwx 1 merijn users    15 Apr 17  2015 CSV.pm -> lib/Text/CSV.pm
-rw-rw-r-- 1 merijn users 56685 Nov 11 08:17 lib/Text/CSV.pm
-rw-rw-rw- 1 merijn users  1029 Aug  8  2014 sandbox/CSV.pm
```

**Comment by teodozjan** [comment]
@Tux I'm not sure why it requires module to be loadable but is supports only metafile now. And checks only for provides. 
https://github.com/teodozjan/pod6-coverage/issues/14

     $ panda look Text::CSV
     $ panda install ./
     $ pod-coverge --anypod
      Str::Text::CSV has no pod

**Comment by Tux** [comment]
That is weird again. It is Text::CSV, not Str::Text::CSV
```
$ find * | grep pod
Text-CSV.pod
```
Should it be renamed to Text::CSV.pod? Should it reside in lib/ ?

**Comment by teodozjan** [comment]
The Str problem fixed here https://github.com/teodozjan/pod6-coverage/issues/15

The second one needs talk. Now Pod::Coverage is not reading pod files at all. If it is wrong I can fix but if doubt I use p6doc as reference.  p6doc is getting confused:

          $ p6doc Text::CSV
          No Pod found in /home/kamil/.rakudobrew/moar-nom/install/share/perl6/site/lib/Text/CSV.pm

I think anything that will be accepted by p6doc should be also fine for Pod::Coverage

**Comment by Tux** [comment]
```
$ wc -l Text-CSV.pod lib/Text/CSV.pm
  2319 Text-CSV.pod
  1663 lib/Text/CSV.pm
```
I don't feel for including the pod in the pm. Just tell me how to rename the pod so it will be installed by panda and found by p6doc. I agree that P::C is just to do the same as p6doc regarding finding files

**Comment by teodozjan** [comment]
@Tux Try now with lib/Text/CSV.pod

**Comment by Tux** [comment]
```
$ ls -l lib/Text/
total 120
-rw-rw-r-- 1 merijn users 56685 Nov 11 08:17 CSV.pm
-rw-rw-r-- 1 merijn users 63066 Nov 17 17:37 CSV.pod
$ pod-coverge --anypod

Correct > pod-coverage --anypod [y|n|E|a]? yes
Could not find Text::CSV in any of:
:
```
Why does it not work **before** a panda install?
So,
```
$ panda install .
:
$ pod-coverage --anypod
===SORRY!=== Error while compiling /pro/3gl/CPAN/Text-CSV6/lib/Text/CSV.pod
Two terms in a row
at /pro/3gl/CPAN/Text-CSV6/lib/Text/CSV.pod:38
------> comma-separated values. An⏏ instance of the Text::CSV class will co
    expecting any of:
        infix
        infix stopper
        postfix
Text::CSV has no pod
```

**Comment by teodozjan** [comment]
Because I didn't have time to separate anypod test from detailed coverage test and I need to put MetaObject into results. I assume for detailed test is obvious that module has to be importable

Anyway you may try something like 

    PERL6LIB=lib pod-coverage --anypod

**Comment by zoffixznet** [comment]
Thanks, everyone. I'm closing this Issue with this plan of action to be implemented:

After cleaning up the build script of the new Mojo-app based modules.perl6.org, I'll add @teodozjan's [POD Coverage](https://github.com/teodozjan/pod6-coverage) module to the build process to evaluate each dists's doc situation and roll it into a [Kwalitee metric](https://github.com/perl6/modules.perl6.org/blob/master/TODO-IDEAS.md#kwalitee) (which will be experimental for now).

Once [dist info pages](https://github.com/perl6/modules.perl6.org/blob/master/TODO-IDEAS.md#dist-information) are added, a blurb about needing docs might also be added (or the page might list methods that are potentially present, but aren't documented).

And these features will be the springboard for someone to find projects to contribute to by writing docs, as well as for authors to be more diligent with respect to writing docs, since now we'll be measuring that.
