### ISSUE TITLE
[RESOLVED in mojo-app branch] sort preference isn't preserved on Back button

### ISSUE THREAD

**Issue by softmoth** [perl6/modules.perl6.org#17]
To repeat:

1. click "Updated" to sort by that column
2. scroll to the middle of the page
3. click a link to visit a module page
4. click *back* in the browser
5. see page sort by name

Perhaps use a `#sort-col` anchor, to avoid re-sorting?

**Comment by zoffixznet** [comment]
This is resolved by the above commit and the Issue will be closed when the branch gets merged and goes live.
