### ISSUE TITLE
[RESOLVED in mojo-app branch] inconvenient sort behavior

### ISSUE THREAD

**Issue by softmoth** [perl6/modules.perl6.org#18]
The sort direction toggle behavior is a little inconvenient.

* The default for date-based columns should be descending sort (recent first)

* The last-used order should be used when clicking on a non-sorted column. For example,
   1. Load modules.perl6.org, notice that it is sorted by Name ascending
   2. Click Description header, it is sorted by Description ascending
   3. Click Name header, it is sorted by Name **descending**

   It should only toggle the sort order when clicking on the current sort header.

**Comment by zoffixznet** [comment]
Just curious, what's the use case for the second issue? (Trying to estimate how useful that would be, since the fix is non-trivial).

**Comment by softmoth** [comment]
I do it a lot when looking through the modules. I like to look at what's happening in the ecosystem, and sort by Updated gives me that. I like to look at some project, look at what's being committed or new issues, etc., and then go back to the list and keep working through them.

I may be an odd one here, and perhaps it's not worth the effort at this time to fix. I can open links in new tab to avoid the re-sort on *back button* as a workaround.

**Comment by zoffixznet** [comment]
Sorry, I meant the second item in the list above:
> The last-used order should be used when clicking on a non-sorted column. For example,
>    Load modules.perl6.org, notice that it is sorted by Name ascending
>    Click Description header, it is sorted by Description ascending
>    Click Name header, it is sorted by Name descending

**Comment by zoffixznet** [comment]
Hm. I don't see a good solution that doesn't require hacking directly on the TableSorter plugin for either of the items in this ticket. 

Adding `sortInitialOrder: 'desc',` to its options cheats a bit that if you click on `Updated` it sorts it by newest first, but then, this cheat will probably not work when we'll add `Added to the ecosystem on` date field.

If anyone else wants to have a go, go ahead :D

**Comment by softmoth** [comment]
Zoffix, thanks. I don't have a specific use case for the last-used-order issue other than just clicking around and expecting things to work "normally". Thanks for looking, I guess this is low priority but would be nice to fix eventually. Perhaps w/ a different plugin?

**Comment by zoffixznet** [comment]
Both of the issues are resolved by the above commit and the Issue will be closed when the branch gets merged and goes live.
