### ISSUE TITLE
Regain Some Screen Real Estate

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#19]
Now that we have more info on the page, we should look into optimizing the shown info to get more screen real estate:

1) The badges: some of them might not be as useful. The 90-day commits badge might be misleading, since some modules now could be "finished" and not require commits. The panda badge might not need to be there.
2) The travis badges could be shrunk down by removing the redundant "build" word. 

This was the discussion on IRC: http://irclog.perlgeek.de/perl6/2015-11-03#i_11475494

**Comment by jonathanstowe** [comment]
:+1:

**Comment by azawawi** [comment]
Fixed in https://github.com/perl6/modules.perl6.org/commit/3c0f2c5241cb8fc8d7b8bdb30e521a06703777fa and https://github.com/perl6/modules.perl6.org/commit/f02f9e06687f3deb063485e3b9481b62711ed710

Please reopen if anything is missing.
