### ISSUE TITLE
JSON output doesn't use proper booleans.

### ISSUE THREAD

**Issue by xfix** [perl6/modules.perl6.org#2]
Example list of modules (with one module):

```json
{
    "Benchmark::Plot": {
        "last_updated": "2011-04-20T13:26:41-07:00",
        "badge_has_tests": null,
        "badge_is_fresh": "",
        "name": "Benchmark::Plot",
        "badge_panda": "1",
        "badge_is_popular": "",
        "description": "Simple benchmark graphing script",
        "badge_has_readme": "http://github.com/colomon/Benchmark-Plot/blob/master/README",
        "auth": "colomon",
        "url": "https://github.com/colomon/Benchmark-Plot/",
        "home": "github",
        "repo_name": "Benchmark-Plot"
    }
}
```

What is the problem? Instead of booleans `true` and `false` (`JSON::true` and `JSON::false`), `1` and `""` is used instead (in one case it's even `null`). The problem is that it's implementation detail, not every language has those values as truthy or falsy. While it isn't important in Perl or JavaScript, it is important, for example in Ruby where `0` and `""` is true.

**Comment by zoffixznet** [comment]
Thanks a lot!
