### ISSUE TITLE
Graphic indicator for Travis CI status

### ISSUE THREAD

**Issue by cygx** [perl6/modules.perl6.org#20]
The status column has been changed to text recently, but some kind of colourful indicator would be nice to have (eg using [these images](http://imgur.com/a/tIFZ8)).

One could even make it into a badge, though this would mean we would lose the ability to sort by the status.

**Comment by zoffixznet** [comment]
:+1: , though the linked images are kinda weird (maybe I'm missing some reference?)

The change was made by @azawawi in reference to Issues #19 .

My thoughts were to just modify the old badge images to remove the "build" word from them. I suppose  text-only will work too, but if we're going with that approach I would suggest:
1) Use CSS to colorize the background of the table cell (green for passing cell, red for failing, gray for others)
2) Add the 'Add travis' button that used to be there. It was a link to an instructional page that would let authors know how to add travis stuff to their repo.

My two cents.

**Comment by cygx** [comment]
>  the mustached man images you linked to are kinda weird

These are the favicons from the Travis site. The generic one looks like this:

![travis man](https://cdn.travis-ci.org/images/favicon-662edf026745110e8203d8cf38d1d325.png)

**Comment by zoffixznet** [comment]
Ah :smile_cat: fair enough :) We should probably shrink them down a bit though, to maintain row height more or less the same as it is now.

**Comment by azawawi** [comment]
Just tested them... They look rather ugly when scaled to 20x20.

**Comment by cygx** [comment]
@azawawi 20x20 is a weird format - perhaps scale to 16x16 and enlarge? Or see if you can find larger versions somewhere on the Travis site (or of course just use a different image set altogether).

**Comment by cygx** [comment]
@azawawi you could probably base them on https://cdn.travis-ci.org/images/dashboard/footer-logo-53fdfcfedc0cc9d0985d85f273579f40.svg

**Comment by azawawi** [comment]
Hopefully the latest fixes (once they go live) will resolve this :+1: 

I went with removing "build" prefix and fixing the sort order behavior.

**Comment by jonathanstowe** [comment]
It appears the CSS has gone walkies on the latest build :-\

**Comment by zoffixznet** [comment]
@jonathanstowe works fine to me. Try pressing CTRL+F5 to do a hard refresh. The file was moved, so maybe that's why.

![screen](https://cloud.githubusercontent.com/assets/5747918/10940971/537ec0d6-82d7-11e5-9f31-e633363b4610.png)

**Comment by azawawi** [comment]
Sorry for the updates but it is expected given that we do not have a testing server.

**Comment by jonathanstowe** [comment]
All fine now.  Looks good.
