### ISSUE TITLE
Reduce Number of HTTP Requests -> Sprites

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#21]
Currently, each page load generates **51** HTTP requests to fetch images. That number is growing any time someone adds a logotype to their repo.

We can reduce all of these to **a single request** if we [sprite the images](https://en.wikipedia.org/wiki/Sprite_%28computer_graphics%29#Sprites_by_CSS), thereby improving load speed of the page and hammering the server less.

I can easily add this feature if the server admin ( @moritz ?) installs additional Perl modules and Debian packages needed for [the module that can auto-generate sprites](https://metacpan.org/pod/Mojolicious::Plugin::AssetPack).

This is what's needed to be installed:
```bash
apt-get install libpng12-dev;
cpanm Mojolicious::Plugin::AssetPack Imager Imager::File::PNG Imager::File::GIF Imager::File::JPEG;
```
If you want to test that the spriter works, you can download and run this app:
```bash
cd $(mktemp -d);
git clone https://github.com/zoffixznet/debug.git .;
git checkout c91f35a87dd64297a43de1766330eb514251e699;
morbo app.pl;
```
The app will now start up on port `3000` and when visiting `http://localhost:3000` you should see a page with two pics on it:
![panda](https://cloud.githubusercontent.com/assets/5747918/11006630/b1c2d58a-8492-11e5-91ad-62055e33da45.png)

Let me know whether the extra software above can be installed and I'll write this feature.

Cheers,
ZZ

**Comment by jonathanstowe** [comment]
:+1:

**Comment by moritz** [comment]
I'm setting up a prelbrew environment for the modules.perl6.org build script, so that we can install perl 5 modules painlessly. (There's no Debian package for Mojolicious::Plugin::AssetPack). I'll let you know when I'm done.

**Comment by azawawi** [comment]
Interesting idea. What about simply using http://datatables.net pagination to make sure we can scale in the future. The images can also be Base64 encoded into the JSON structure that a data tables needs.

**Comment by zoffixznet** [comment]
> What about simply using http://datatables.net pagination to make sure we can scale in the future. 

My hope is by the time we'd need to scale, we'd have a working version of Perl 6 PAUSE/MetaCPAN, so the point would be moot :)

The current problem with pagination is our search relies on a single table. There might be a way to make it work, but I think those dev resources would be best spent on PAUSE/MetaCPAN instead.

**Comment by moritz** [comment]
Ok, on the perlbrew front: updating the modules list with a perl 5.22 generates an empty list, no errors :(

No idea what's wrong.

**Comment by zoffixznet** [comment]
@moritz is IO::Socket::SSL installed?

**Comment by moritz** [comment]
@zoffixznet it wasn't, thanks. Now it works, and your additionally requested modules are also installed.

**Comment by zoffixznet** [comment]
Awesome! Thanks a lot.
