### ISSUE TITLE
Broken Images / Missing sprite.css

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#22]
Just a note, in case anyone notices the current breakage and starts trying to fix it:

The breakage was done by the commit implementing #21 . The new code requires `Mojolicious::Plugin::AssetPack` (and supporting modules), which currently are not installed. Server admin @moritz will install those when they have a chance, and then the site should work fine.

To resolve the issue:
```bash
apt-get install libpng12-dev;
cpanm Imager::File::PNG Mojolicious::Plugin::AssetPack 
```

Cheers,
ZZ

**Comment by moritz** [comment]
My bad, I messed it up in the first place. But the sprites look OK now, so I guess my fix worked.
