### ISSUE TITLE
[RESOLVED in mojo-app branch] Improvement to Sorting

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#24]
Here are some problems / potential improvements for the current sorting plugin:

* #21 needs custom edits to use a sprite instead of individual images. We don't actually need images there at all; we can use Unicode chars. If we do that, we likely can get rid of custom edits (just use CSS `content` property to display proper Unicode char)
* We have Issues #18 (inconvenient sorting) and #17 (sort not preserved on `Back` button). #23 is sorta related too

@azawawi also mentioned http://datatables.net/ that provides pagination. So, instead of doing anything about the above, we should see if the datatable stuff is better.

**Comment by moritz** [comment]
My experience with datatables is that that it does pretty much everything you wish for, but it is very opionated about how the backend should look like. Just something to keep in mind.

(FWIW I'd be fine with a mojolicious app or similar serving modules.perl6.org, doesn't need to stay statically generated content).

**Comment by zoffixznet** [comment]
> FWIW I'd be fine with a mojolicious app or similar serving modules.perl6.org

Woohoo \o/ Then expect to see a Mojolicious app soon enough :smile_cat: (that will take care of #23 easily with AssetPack plugin)
