### ISSUE TITLE
[RESOLVED IN new-db-builder] GitHub Rate Limit of 5000/hr

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#36]
GitHub has a rate limit of 5000 API queries per hour. We currently make 3 requests per dist and the updater script runs twice per hour. This means we'll hit the limit when our ecosystem reaches 833 modules, which is about 80% more modules than we currently have.

Taking care of this Issue will be easy, once the `new-db-builder` branch is merged. We'll just perpetually run the build script, with sufficient delays between fetching info for each dist so we don't hit the API limit. The cron job will be there just to pull updates for the repo and ensure the build script is alive.

**Comment by sylvarant** [comment]
Can't we work around this limit by eventually moving to a module system where people submit finished releases as .zip/.tar files, instead of just linking to the github repo?
The [OCaml module system](https://github.com/ocaml/opam-repository), for example, uses that method.

**Comment by zoffixznet** [comment]
@sylvarant, I think that's an issue in itself and is large enough that its discussion shouldn't be done in this Issue :smile_cat:, even if such an implemention will resolve it. Especially since this Issue can be closed after literally adding `sleep 5` [here](https://github.com/perl6/modules.perl6.org/blob/new-db-builder/lib/ModulesPerl6/DbBuilder.pm#L89).

jdv79 has some sort of P6 MetaCPAN in the works that should work as you propose. But [last time I discussed the future of modules.perl6.org](http://irclog.perlgeek.de/perl6/2015-11-11#i_11520706), the result was that [we'll actually have two ecosystems](http://irclog.perlgeek.de/perl6/2015-11-11#i_11520741). The MetaCPAN where people upload stuff the way you describe and the current modules.perl6.org system where people just link their repo hosted at X and it essentially gets updated whenever they push commits to master. With the MetaCPAN version maybe making occasional snapshots of the loose-and-fast modules.perl6.org dists.

How well that will work out? We're yet to see. We do have the obvious problem that production-ready software probably can't easily declare it that it requires version X of module Y from a fluid repo where stuff can be broken at any moment. So far, there wasn't much of a discussion onther than [this mention](http://irclog.perlgeek.de/perl6/2015-11-24#i_11589015) that I know of.

Maybe modules.perl6.org will end up some sort of a Bleeding Edge MetaCPAN :joy_cat:
