### ISSUE TITLE
Add Dists to Ecosystem from the Site

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#40]
Instead of asking people to make PRs to the [ecosystem](https://github.com/perl6/ecosystem/) to add their dists, we can make a special page on the [modules.perl6.org](http://modules.perl6.org) where users can submit their dists for inclusion into the ecosystem. This will also allow much easier inclusion of dists from other Dist Sources (e.g. GitLab).

#### How it Works

1) User visits, say `/upload`, and gives the site a link to the repo of their dist. 
2) The site normalizes the link (we could get a link to repo using `git://` or `https://`, to META, to raw META, etc)
3) The site looks at the repo contents to analyze for common problems (JSON errors in META or missing required fields)
4) Potentially, the site can also make analysis and offer the dist author suggestions for improving it (adding a README and tests).
5) The site then makes a commit to the [ecosystem](https://github.com/perl6/ecosystem/), adding the dist.
6) ???
7) PROFIT!

#### Benefits
1) Automated check for problems in dists that immediately gives feedback to dist author instead of just showing up in logs
2) Encourage people who do not like GitHub to contribute their dists using different Dist Sources
3) Make it easier for people who are unfamiliar with git or making PRs to add dists
4) Less work for members of [Perl 6 GitHub Organization](https://github.com/perl6/), since we won't need to check each PR for problems and manually merge it.

**Comment by coke** [comment]
+1

**Comment by zoffixznet** [comment]
I believe this is superceeded by the PAUSE/CPAN/MetaCPAN efforts. Closing.
