### ISSUE TITLE
Add new Dist Source for SHELTERed modules

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#49]
We currently have a [SHELTER](https://github.com/perl6/ecosystem/tree/master/SHELTER) in the ecosystem repo that seems to be a collection of abandoned modules, available for adoption.

We should add a different Dist Source that handles these and display them on the site slightly different, to attract the attention of potential adopters.

We likely should add a `source` field to the Dists model to know where dists is from and display it accordingly on the site.

P.S.: we currently do have two sheltered dists

**Comment by moritz** [comment]
I'd propose we get rid of SHELTERed module, and keep the links to them somewhere out of the way (the perl6/mu repo is a good place for that, IMHO)
