### ISSUE TITLE
Website says not setup when .travis.yml is present and works

### ISSUE THREAD

**Issue by sylvarant** [perl6/modules.perl6.org#50]
Both my [Avro](https://github.com/sylvarant/Avro) and [Compress::Brotli](https://github.com/sylvarant/Compress-Brotli) modules are displayed as not set up on modules.perl6 but if you click on them it does take you to the correct travis page ?

**Comment by scmorrison** [comment]
This is also happening for [AWS::Pricing](https://github.com/scmorrison/perl6-aws-pricing). I notice that it appears as green / passing on http://modules.perl6.org/#q=aws for some time following a travis build. But then after a while it just reverts back to the "not set up" message.
