### ISSUE TITLE
Track `master` branch for Travis

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#51]
Currently, looks like the latest build is tracked by travis, but we need to track `master`, which that's what I believe panda installs.

The current issue is the modules page shows, say [FTP  module as failing](http://modules.perl6.org/#q=FTP), but in reality `master` passes and it's only the `develop` branch that's failing.

**Comment by JJ** [comment]
Would this be enough?

**Comment by zoffixznet** [comment]
Yeah, I think this is fixed
