### ISSUE TITLE
“You can link to a search query, like so:”

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/modules.perl6.org#55]
It says:

> You can link to a search query, like so: http://modules.perl6.org/#q=Test

Why not provide the current link instead of rather useless link to ``q=Test``? :)

**Comment by zoffixznet** [comment]
The link looks fine to me. What's the issue with it?

**Comment by AlexDaniel** [comment]
If you type “Hello world” into the search form then it should say:

> You can link to a search query, like so: http://modules.perl6.org/#q=Hello+World

However, I've just noticed that it actually changes the current url right in the browser. That's probably good enough.

**Comment by zoffixznet** [comment]
Ah, I see the confusion. That's just a site tip and it's not aware of what's currently typed in the search box. It just randomly pulls one tip from this file: https://github.com/perl6/modules.perl6.org/blob/master/site-tips.txt
