### ISSUE TITLE
Need transition plan for move to CPAN

### ISSUE THREAD

**Issue by tbrowder** [perl6/modules.perl6.org#63]
The current ecosystem seems to have no transition path for merging with CPAN.  We seem stuck with a system which clearly can be improved, yet we as a community seem unable to envision any way ahead to integrate the current system with CPAN.

**Comment by zoffixznet** [comment]
That's not quite accurate. @jdv and others have been working on converting a MetaCPAN clone to be usable by Perl 6, including automated transition of the current ecosystem by autouploading modules. Moreover, @shadowcat-mst fairy recently has sent out a public announcement of the new stage of testing of PAUSE to accommodate Perl 6.

So while the effort isn't moving at breakneck speed and could use more publicity and information to, hopefully, inspire more volunteers to pitch in, we do have a plan and a vision.

**Comment by tbrowder** [comment]
Okay, I stand corrected.  I an very interested in the auto-uploading aspects but was essentially told any effort on the current system was wasted.  Can you please point to the @shadowcat-mst announcement?

**Comment by zoffixznet** [comment]
> Can you please point to the @shadowcat-mst announcement?

Here: http://shadow.cat/blog/matt-s-trout/the-psixdists-experiment/

**Comment by raiph** [comment]
See also https://perl6advent.wordpress.com/2015/12/21/perl6-and-cpan/

**Comment by tbrowder** [comment]
Thanks!

**Comment by supernovus** [comment]
Random comment from somewhat of an outsider these days, what does CPAN offer that the current ecosystem doesn't? I never in the years I did Perl 5 stuff, figure out how to get things uploaded to CPAN. With Perl 6, I commit to Github, and as long as that repo is in the ecosystem, it's updated. What could be simpler than that?

**Comment by zoffixznet** [comment]
> I never in the years I did Perl 5 stuff, figure out how to get things uploaded to CPAN. 

It's a simple file upload field. DZIL and many other tools offer a one-command upload, right from your terminal.

> I commit to Github [...] What could be simpler than that?

Simpler for whom? The goal here is not to just dump code into a pile, but for a robust system that can be relied upon, especially by critical systems.

1. There's no guarantee that my 300,000+ codebase that depends on Foo will still work after your commit. In the current state, you can't even guarantee two installs of version v1.2.3 install exact same code.
2. An author can have a shitfit and just nuke their repo, and all of a sudden your 300,000+ codebase doesn't even work ([leftpad](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/) anyone?)
3. An author can overwrite their repo and/or start versioning it all over and you get an even messier versioning hell than in point 1.
4. The current system requires authors accept all of terms and conditions and have an account on either GitHub or GitLab—services Perl 6 community has no relation to. Violation of those terms or decision to close those accounts, means all of their work is removed from Perl 6 Ecosystem *in its entirety* (see point 2)
5. The current system requires module authors to be familiar with `git`. For a language that aims to be welcoming to beginners, especially of a young age, adding a whole 'nuther learning curve should be avoided if possible.

With CPAN, on the other hand, it's very hard to upload a distro with same or lower version, guaranteeing the code that works for me today with Foo v1.2.3 will work with it a year from now. And a network of mirrors, along with backpan, ensure the code is still there to use, regardless of what happens to the primary repo. Lastly, as long as distro format is followed, CPAN doesn't care if you're familiar with git, svn, mercurial, or none of them.

In summation, our current system is only good for toy projects and fails miserably for anything requiring stability.

**Comment by supernovus** [comment]
Thank you. That's very informative. I'm glad CPAN has gotten easier to use from what I remember (which to be honest was probably 15 years ago.) It was one of those things like the old Perl 5 bug tracker that seemed way more convoluted than necessary.

**Comment by supernovus** [comment]
The versioning thing is definitely something that seems essential. Is there a way with the current ecosystem to install an older version if it's required by a dependency?

**Comment by zoffixznet** [comment]
> Is there a way with the current ecosystem to install an older version if it's required by a dependency?

As far as I know, nope. Aside from manually digging up the commit that has it and giving the URL to `zef` directly to install from.

**Comment by tbrowder** [comment]
Never missing an opportunity to not let a dead horse die: I still think we could mod the current system to do the right thing  without going the complete CPAN route.

**Comment by zoffixznet** [comment]
> I still think we could mod the current system to do the right thing without going the complete CPAN route.

And which of CPAN's features you think we do not need? You're implying it's less work to create something suitable from scratch than modify existing piece of that has **21 years** worth of debugging to handle all the edge cases in it. I'm highly dubious of that.

**Comment by tbrowder** [comment]
I can't say.  But I do think we could use the good bits and chunk the bad.  Somewhat (weakly) analogous to P5 => P6.

**Comment by zoffixznet** [comment]
After [CPAN update](https://github.com/perl6/modules.perl6.org/pull/83), looks like this issue is resolved—at least in the scope of this repo.

The site now shows CPAN dists and [`from:cpan`](http://modules.perl6.org/search/?q=from%3Acpan) search qualifier can search for dists only from CPAN.
