### ISSUE TITLE
UI problems with tags

### ISSUE THREAD

**Issue by moritz** [perl6/modules.perl6.org#73]
I just some trouble searching for a module on modules.perl6.org. I wanted to click on the search bar to select it, and at the same time, the tags appeared out of nowhere, making my click land on a random tag instead of the search bar.

And then I had a tag selected, and found no obvious way to unselect the tag; I tried clicking on the tag again, but that didn't work either.

So, I'd like a way for the tags to appear to not steal clicks that were meant for the search bar, and for a way to delete the tag selection.

**Comment by tbrowder** [comment]
+1

**Comment by zoffixznet** [comment]
Thanks. Fixed in https://github.com/perl6/modules.perl6.org/commit/c518c09135f6957386922ca08d32c9d897fa027f
