### ISSUE TITLE
todo checker missed some changes

### ISSUE THREAD

**Issue by zengargoyle** [perl6/modules.perl6.org#75]
http://modules.perl6.org/todo/zengargoyle shows my 3 modules as 'dist has no MANIFEST file'.
However, they all have a 'MANIFEST' file.  The other warnings I cleaned up (no tags in META,
missing version) did disappear from the todo page.

I believe somehow the 'MANIFEST' got missed and is now in the cache as such.  I haven't tried
pushing another commit to my modules to see if it will clear this warning in case you want to
take a look.

**Comment by zoffixznet** [comment]
Fixed in https://github.com/perl6/modules.perl6.org/commit/5db8ada712eb3e4e9a7f2548d0d2700ab60133b5
