### ISSUE TITLE
Implement Smarter Rate Limiter

### ISSUE THREAD

**Issue by zoffixznet** [perl6/modules.perl6.org#79]
Currently we use a static rate limiter that just sleeps for ~~3 seconds~~ [1 second](https://github.com/perl6/modules.perl6.org/commit/1e1d67f1ec) between fetching dists. There's actually a GitHub [API endpoint](https://developer.github.com/v3/#rate-limiting) the builder script can access to see how many requests we still have available and then calculate the rate limit based on that.

In the end, I think this will let it update the site more often, as we'll scale the rate limit to the actual number of dists we have.

**Comment by timo** [comment]
i'd say what we've implemented recently covers this. the updater now does the github requests at "full speed" most of the time.
