### ISSUE TITLE
Which modules is on CPAN?

### ISSUE THREAD

**Issue by szabgab** [perl6/modules.perl6.org#82]
Would it be possible to also include an indication which module is on CPAN?
I wonder if it would be an improvement to the stability of the ecosystem if more people releases their stable versions to CPAN?

And then if an when #88 is implemented, add this information to the /recent page as well.

**Comment by zoffixznet** [comment]
Fixed with the CPAN update. The dist icon shows where the dist is from and [`from:cpan`](http://modules.perl6.org/search/?q=from%3Acpan) search qualifier can show all dists from CPAN
