### ISSUE TITLE
Modules with email in author field break

### ISSUE THREAD

**Issue by the-eater** [perl6/modules.perl6.org#84]
Currently when a module has the email of the author in the authors field (like `eater <perl6@eaterofco.de>`) the link generated to the module doesn't work: `http://modules.perl6.org/dist/TagLibC:github:eater%20%3Cperl6@eaterofco.de%3E`

**Comment by zoffixznet** [comment]
Thanks. Fixed: [https://modules.perl6.org/dist/TagLibC:github:eater%20%3Cperl6@eaterofco.de%3E](https://modules.perl6.org/dist/TagLibC:github:eater%20%3Cperl6@eaterofco.de%3E)
