### ISSUE TITLE
the /repo/ URLs give you the zipfile for cpan dists, not the repo

### ISSUE THREAD

**Issue by timo** [perl6/modules.perl6.org#87]

**Comment by zoffixznet** [comment]
That works like designed, even though `repo` might be a misnomer now that we have CPAN.

`/repo/` end point points to dist source, like GitHub/GitLab repo, or the CPAN archive. `/dist/` points to human-vieable contents of the dist (currently still a repo for GitHub/GitLab; for CPAN a modules.perl6.org file viewer page)

**Comment by zoffixznet** [comment]
> That works like designed

Just to clarify: this issue still needs to be fixed and we need an endpoint that would redirect to dist's repo, even for CPAN dists (with current functionality of `/repo/` stuffed under some other route)
