### ISSUE TITLE
Some angle brackets not escaped in README.md code

### ISSUE THREAD

**Issue by softmoth** [perl6/modules.perl6.org#92]
Viewing the source for http://modules.perl6.org/dist/Number::Denominate:cpan:ZOFFIX shows this issue. For example, the following line:

```say denominate 449, :units( foo =&gt; 3, <bar boors> =&gt; 32, &#39;ber&#39; );```

The `<bar boors>` should be `&lt;bar boors&gt;`, but those angle brackets are not escaped. The `=&gt;` bracket is, though. I'm not seeing where the escaping is being done, unfortunately, to suggest a fix.

The result of this bug is that the displayed README content is missing important content.

**Comment by zoffixznet** [comment]
Need to add `xml_escape` to the list of imported functions [here](https://github.com/perl6/modules.perl6.org/blob/61bb5c6570858b8d86189e46e2092ea41cc8e093/lib/ModulesPerl6/Controller/Dist.pm#L11) and then add:

```perl
$lang = xml_escape $lang;
$code = xml_escape $code;
```

Before this line: https://github.com/perl6/modules.perl6.org/blob/61bb5c6570858b8d86189e46e2092ea41cc8e093/lib/ModulesPerl6/Controller/Dist.pm#L166
